# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170326_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 27, 10, 6, 44, 221000, tzinfo=utc)),
        ),
    ]
