# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170327_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 28, 9, 10, 55, 537000, tzinfo=utc)),
        ),
    ]
